blank_issues_enabled: true

contact_links:
  - name: 📚 dstack Documentation
    url: https://dstack.ai/docs
    about: Official dstack documentation for general dstack questions
  - name: 💬 dstack GitHub Community
    url: https://github.com/dstackai/dstack
    about: Join the dstack GitHub community discussions
  - name: 💬 dstack Discord Community
    url: https://discord.gg/u8SmfwPpMd
    about: Join the dstack Discord community discussions
  - name: 🔧 SGLang Documentation
    url: https://github.com/sgl-project/sglang
    about: SGLang repository and documentation
